---
# Default variables for zabbix_agent role
zabbix_server: "10.209.5.253"
zabbix_server_active: "10.209.5.253"
zabbix_agent_hostname: "{{ ansible_hostname }}"
zabbix_agent_port: 10050
zabbix_agent_listenip: "0.0.0.0"
zabbix_agent_conf: "/etc/zabbix_agentd.conf"
