
- name: Delete file if it exists
  hosts: test
  become: yes
  vars:
    rra_test_file: /tmp/ansible-test.txt

  tasks:
    - name: Remove test file
      ansible.builtin.file:
        path: "{{ rra_test_file }}"
        state: absent